version: '3'
services:
  app:
    command: npm start
    build:
      context: node
    networks:
      - nodenet
    depends_on:
      - mysql
    entrypoint: dockerize -wait tcp://mysql:3306 timeout 20s docker-entrypoint.sh  
    container_name: app
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - /home/emily/desafio-node/node:/usr/app

  mysql:
    restart: always
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    tty: true
    volumes:
      - /home/emily/desafio-node/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: emilymartins/nginx:prod
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"

networks:
  nodenet:
    driver: bridge
